# Build stage
FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
COPY buf.gen.yaml ./
RUN npm ci || npm install

COPY . .

ARG REACT_APP_API_URL
ARG REACT_APP_SERVER_URL
ARG REACT_APP_SERVER_PORT
ARG REACT_APP_SPOTIFY_CLIENT_ID
ARG REACT_APP_YOUTUBE_CLIENT_ID

ENV REACT_APP_API_URL=$REACT_APP_API_URL \
    REACT_APP_SERVER_URL=$REACT_APP_SERVER_URL \
    REACT_APP_SERVER_PORT=$REACT_APP_SERVER_PORT \
    REACT_APP_SPOTIFY_CLIENT_ID=$REACT_APP_SPOTIFY_CLIENT_ID \
    REACT_APP_YOUTUBE_CLIENT_ID=$REACT_APP_YOUTUBE_CLIENT_ID

RUN npm run build

# Runtime stage
FROM nginx:1.27-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080
